version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis  # Zmienna środowiskowa na host Redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"